services:
  drome-compare:
    build: .
    command: sh -c "node src/initDB.js && node src/index.js"
    restart: unless-stopped
    ports:
      - "127.0.0.1:3111:3000"
    volumes:
      - "./db:/app/db"
